name: style and tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
          path: "backend/self-bi/engine"
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          cd backend
          make unit
        env:
          ENV: testing
          MY_VARIABLE: value
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_SERVER_HOSTNAME: ${{ vars.DATABRICKS_SERVER_HOSTNAME }}
          DATABRICKS_HTTP_PATH: ${{ vars.DATABRICKS_HTTP_PATH }}
          DATABRICKS_CATALOG: ${{ vars.DATABRICKS_CATALOG }}
          DATABRICKS_SCHEMA: ${{ vars.DATABRICKS_SCHEMA }}
          WAREHOUSE_ID: ${{ vars.WAREHOUSE_ID_RA_DATABRICKS_PROD }}
          MESSAGE_FROM: ${{ vars.MESSAGE_FROM }}
          CLIENT_ID: ${{ secrets.CLIENT_ID_RA_DATABRICKS_PROD }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET_RA_DATABRICKS_PROD }}
          APP_HOST: ${{ vars.APPHOST_PROD }}
          ENVIRONMENT: ${{ vars.DEV_ENVIRONMENT_NAME }}
          SERVICE_PRINCIPAL_CLIENT_ID: ${{ secrets.SERVICE_PRINCIPAL_CLIENT_ID }}
          SERVICE_PRINCIPAL_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_CLIENT_SECRET }}
